<script lang="ts">
	import * as api from '$lib/api';
	import { loadExportPreferences, type ExportPreferences } from '$lib/exportPreferences';
	import { buildPlecoExport } from '$lib/pleco';
	// buildXlsxBlob's own dynamic import of the `exceljs` library (see
	// xlsxExport.ts) is where the real bundle-weight deferral happens -
	// this import itself can stay static, since xlsxExport.ts's own
	// top-level imports are already cheap/shared with pleco.ts.
	import { buildXlsxBlob } from '$lib/xlsxExport';
	import { sanitizeFilename, type ExportWordData, type ExportableWord } from '$lib/exportData';
	import { getContextChars } from '$lib/contextPreferences';

	type ExportFormat = 'pleco' | 'xlsx';

	// Opened from analyze/[id]/+page.svelte's toolbar. Everything the user
	// might want to change per-export lives on the Account page
	// (ExportPreferences, backend-persisted - see exportPreferences.ts) -
	// this dialog is deliberately thin: load those settings plus the bulk
	// per-word data, show a read-only summary of the settings with a link
	// to go edit them, and offer the one thing that's genuinely an
	// export-time decision (respect the current filter or not) before
	// triggering the download.
	let {
		analysisId,
		textTitle,
		allWords,
		filteredWords,
		onClose,
	}: {
		analysisId: number;
		textTitle: string | null;
		allWords: ExportableWord[];
		filteredWords: ExportableWord[];
		onClose: () => void;
	} = $props();

	let loading = $state(true);
	let error = $state('');
	let prefs: ExportPreferences | null = $state(null);
	let exportData: ExportWordData[] | null = $state(null);
	// Defaults to respecting the current filter - "what I'm looking at is
	// what I get" is the least-surprising default; unchecking it exports
	// every word in the analysis regardless of the filter bar's state.
	let respectFilter = $state(true);
	// Pleco's flashcard .txt is the original format this dialog supported
	// and stays the default - .xlsx (xlsxExport.ts) is the newer, second
	// option, picked explicitly rather than remembered across visits (same
	// "just default to the simplest thing" reasoning the filter checkbox
	// above already uses).
	let format: ExportFormat = $state('pleco');
	// True only while a download is actually being built - mainly matters
	// for .xlsx, where loading the underlying library (and its web worker)
	// on first use takes a perceptible moment; the button reflects this so
	// a slow tap doesn't look like nothing happened.
	let exporting = $state(false);
	// Set once a download has actually fired (see handleExport) - a mobile
	// browser's own download UI is easy to miss entirely (no visible
	// progress, no obvious "saved" toast the way a desktop browser's
	// download tray gives you), so this dialog now surfaces its own
	// explicit confirmation instead of just closing the instant the
	// browser is asked to save the file. Holds the filename so the
	// confirmation can name the exact file that landed in Downloads.
	let downloadedFilename: string | null = $state(null);

	$effect(() => {
		loading = true;
		error = '';
		Promise.all([loadExportPreferences(), api.getExportData(analysisId, getContextChars())])
			.then(([loadedPrefs, data]) => {
				prefs = loadedPrefs;
				exportData = (data as { words: ExportWordData[] }).words;
			})
			.catch((e: unknown) => {
				error = e instanceof Error ? e.message : 'Failed to load export data';
			})
			.finally(() => {
				loading = false;
			});
	});

	const wordsToExport = $derived(respectFilter ? filteredWords : allWords);

	// Short, read-only recap of the account-level settings - not editable
	// here, just enough context to know what's about to be exported before
	// clicking through to /profile to change anything.
	const sourcesSummary = $derived.by(() => {
		if (!prefs || !prefs.includeDefinitions) return null;
		const s = prefs.definitionSources;
		const parts: string[] = [];
		if (s.corpusFrequency) parts.push('Corpus frequency');
		if (s.hsk) parts.push('HSK');
		if (s.cedict) parts.push('CC-CEDICT');
		const userScopes = [s.userGlobal && 'Global', s.userText && 'This text', s.userAnalysis && 'This analysis'].filter(Boolean);
		if (userScopes.length > 0) parts.push(`Your definitions (${userScopes.join(', ')})`);
		if (s.autoGenerated) parts.push('Auto-generated');
		return parts.length > 0 ? parts.join(', ') : 'None selected';
	});

	// Second recap line for the additional-info toggles - a separate group
	// from definitionSources above since these aren't "word definition"
	// content at all (a count/score/sentence list/note), just other data
	// this export can also carry.
	const additionalInfoSummary = $derived.by(() => {
		if (!prefs) return null;
		const parts: string[] = [];
		if (prefs.includeFamiliarity) parts.push('Familiarity');
		if (prefs.includeSampleSentences) parts.push('Sample sentences');
		if (prefs.includeContext) parts.push('Context');
		if (prefs.includeGlobalNote) parts.push('Global note');
		return parts.length > 0 ? parts.join(', ') : 'None selected';
	});

	// Pleco's categories and .xlsx's sheets are the same underlying
	// Main/Extra grouping (sourceCategory, wordDisplay.ts) - only the noun
	// describing them, and whether the text's title is baked into each name
	// (Pleco) or just the file itself (.xlsx, one file per text already),
	// differs per format.
	const groupingSummary = $derived(
		format === 'pleco'
			? `grouped into Main/Extra categories under "${textTitle ?? 'Untitled text'}"`
			: 'grouped into Main/Extra sheets'
	);

	function downloadBlob(filename: string, blob: Blob) {
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = filename;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}

	async function handleExport() {
		if (!prefs || !exportData) return;
		exporting = true;
		error = '';
		try {
			if (format === 'pleco') {
				const categoryTitle = textTitle ?? 'Untitled text';
				const content = buildPlecoExport(categoryTitle, wordsToExport, exportData, prefs);
				const filename = `${sanitizeFilename(textTitle)}.txt`;
				downloadBlob(filename, new Blob([content], { type: 'text/plain;charset=utf-8' }));
				downloadedFilename = filename;
			} else {
				const blob = await buildXlsxBlob(wordsToExport, exportData, prefs);
				const filename = `${sanitizeFilename(textTitle)}.xlsx`;
				downloadBlob(filename, blob);
				downloadedFilename = filename;
			}
			// Stay open and show a confirmation rather than closing
			// immediately - see downloadedFilename's own docstring above for
			// why (a mobile browser gives no feedback of its own).
		} catch (e: unknown) {
			error = e instanceof Error ? e.message : 'Failed to start the download';
		} finally {
			exporting = false;
		}
	}
</script>

<div class="fixed inset-0 z-40 flex items-center justify-center bg-black/30 p-4" onclick={onClose} role="presentation">
	<div
		class="bg-white dark:bg-slate-900 rounded-lg shadow-lg w-full max-w-md p-6"
		onclick={(e) => e.stopPropagation()}
		role="presentation"
	>
		<h2 class="text-sm font-semibold text-gray-700 dark:text-slate-300 mb-4">Export</h2>

		{#if downloadedFilename}
			<!-- Explicit success confirmation, held open until the user
			     dismisses it - see downloadedFilename's own docstring for why
			     this dialog doesn't just close the instant the download
			     fires. -->
			<div class="flex items-start gap-2 bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/30 text-emerald-700 dark:text-emerald-400 px-3 py-2.5 rounded text-sm mb-4">
				<svg class="w-4 h-4 mt-0.5 shrink-0" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
					<path d="M4 10.5l3.5 3.5L16 6" />
				</svg>
				<span>Downloaded <span class="font-medium">{downloadedFilename}</span>.</span>
			</div>
			<div class="flex justify-end">
				<button
					onclick={onClose}
					class="text-sm px-4 py-1.5 bg-blue-600 dark:bg-blue-500 text-white rounded hover:bg-blue-700 dark:hover:bg-blue-600"
				>
					Done
				</button>
			</div>
		{:else if loading}
			<p class="text-sm text-gray-500 dark:text-slate-400">Loading…</p>
		{:else if error}
			<div class="bg-red-50 dark:bg-red-500/10 border border-red-200 dark:border-red-500/30 text-red-700 dark:text-red-400 px-3 py-2 rounded text-sm mb-3">
				{error}
			</div>
		{:else if prefs}
			<div class="mb-4">
				<span class="block text-xs text-gray-500 dark:text-slate-400 mb-1.5">Format</span>
				<div class="inline-flex rounded-md border border-gray-200 dark:border-slate-700 overflow-hidden">
					<button
						type="button"
						onclick={() => (format = 'pleco')}
						aria-pressed={format === 'pleco'}
						class="text-sm px-3 py-1.5 {format === 'pleco'
							? 'bg-blue-600 dark:bg-blue-500 text-white'
							: 'bg-white dark:bg-slate-900 text-gray-600 dark:text-slate-400 hover:bg-gray-50 dark:hover:bg-slate-800'}"
					>
						Pleco (.txt)
					</button>
					<button
						type="button"
						onclick={() => (format = 'xlsx')}
						aria-pressed={format === 'xlsx'}
						class="text-sm px-3 py-1.5 border-l border-gray-200 dark:border-slate-700 {format === 'xlsx'
							? 'bg-blue-600 dark:bg-blue-500 text-white'
							: 'bg-white dark:bg-slate-900 text-gray-600 dark:text-slate-400 hover:bg-gray-50 dark:hover:bg-slate-800'}"
					>
						Excel (.xlsx)
					</button>
				</div>
			</div>

			<dl class="text-xs text-gray-500 dark:text-slate-400 space-y-1 mb-4">
				{#if format === 'pleco'}
					<!-- Pleco-only setting - it's the dedicated 2nd tab-separated
					     field a Pleco card has. The .xlsx format has no equivalent
					     standalone Pinyin column, so this row would be misleading
					     to show while Excel is selected. -->
					<div class="flex justify-between gap-4">
						<dt>Pinyin</dt>
						<dd class="text-gray-700 dark:text-slate-300">{prefs.includePinyin ? 'Included' : 'Not included'}</dd>
					</div>
				{/if}
				<div class="flex justify-between gap-4">
					<dt>Definitions</dt>
					<dd class="text-gray-700 dark:text-slate-300 text-right">{sourcesSummary ?? 'Not included'}</dd>
				</div>
				<div class="flex justify-between gap-4">
					<dt>Additional info</dt>
					<dd class="text-gray-700 dark:text-slate-300 text-right">{additionalInfoSummary}</dd>
				</div>
			</dl>
			<a href="/profile" class="text-xs text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 block mb-4">
				Edit export settings
			</a>

			<label class="flex items-center gap-2 text-sm text-gray-700 dark:text-slate-300 mb-4">
				<input type="checkbox" bind:checked={respectFilter} class="rounded border-gray-300" />
				Respect current filters
			</label>

			<p class="text-xs text-gray-400 dark:text-slate-500 mb-4">
				{wordsToExport.length} word{wordsToExport.length === 1 ? '' : 's'} will be exported, {groupingSummary}.
			</p>

			<div class="flex justify-end gap-2">
				<button
					onclick={onClose}
					class="text-sm px-4 py-1.5 text-gray-600 dark:text-slate-400 hover:text-gray-800 dark:hover:text-slate-200"
				>
					Cancel
				</button>
				<button
					onclick={handleExport}
					disabled={wordsToExport.length === 0 || exporting}
					class="text-sm px-4 py-1.5 bg-blue-600 dark:bg-blue-500 text-white rounded hover:bg-blue-700 dark:hover:bg-blue-600 disabled:opacity-50"
				>
					{exporting ? 'Exporting…' : 'Export'}
				</button>
			</div>
		{/if}
	</div>
</div>
