"""create user preferences table

Revision ID: 7412ba91e81d
Revises: c974b5406983
Create Date: 2026-09-13 17:29:08.946985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7412ba91e81d'
down_revision: Union[str, Sequence[str], None] = 'c974b5406983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Trimmed by hand from the autogenerated diff: this migration is scoped
    # to user_preferences only. Autogenerate also picked up unrelated
    # pre-existing drift (a missing analysis_results.analysis_id index, and
    # word_visibility.created_at/updated_at showing as nullable in the DB
    # vs. NOT NULL in models.py) that predates this feature - left alone
    # here rather than silently folded into an unrelated migration.
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_index('ix_user_preferences_user_key', 'user_preferences', ['user_id', 'key'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_user_preferences_user_key', table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
