"""create known words tables

Revision ID: 777314dda522
Revises: dcb95a30956e
Create Date: 2026-07-01 00:16:01.263874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777314dda522'
down_revision: Union[str, Sequence[str], None] = 'dcb95a30956e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('freq_combined', sa.BigInteger(), nullable=True),
    sa.Column('hsk_v2_2012', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_v3_2021', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_v3_2026', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_words_word'), 'dictionary_words', ['word'], unique=True)
    op.create_table('hsk_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(), nullable=False),
    sa.Column('radical', sa.String(), nullable=True),
    sa.Column('hsk_v2_2012', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_v3_2021', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_v3_2026', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_frequency', sa.Integer(), nullable=True),
    sa.Column('pos', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsk_entries_simplified'), 'hsk_entries', ['simplified'], unique=True)
    op.create_table('word_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('blog', sa.BigInteger(), nullable=True),
    sa.Column('literature', sa.BigInteger(), nullable=True),
    sa.Column('news', sa.BigInteger(), nullable=True),
    sa.Column('tech', sa.BigInteger(), nullable=True),
    sa.Column('weibo', sa.BigInteger(), nullable=True),
    sa.Column('combined', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_frequencies_word'), 'word_frequencies', ['word'], unique=True)
    op.create_table('garbage_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garbage_words_user_id'), 'garbage_words', ['user_id'], unique=False)
    op.create_index('ix_garbage_words_user_word', 'garbage_words', ['user_id', 'word'], unique=True)
    op.create_table('hsk_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('traditional', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('numeric_transcription', sa.String(), nullable=True),
    sa.Column('meanings', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('classifiers', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['hsk_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsk_forms_entry_id'), 'hsk_forms', ['entry_id'], unique=False)
    op.create_table('input_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_texts_user_id'), 'input_texts', ['user_id'], unique=False)
    op.create_table('known_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('familiarity', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('familiarity IS NULL OR (familiarity >= 1 AND familiarity <= 5)', name='ck_known_words_familiarity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_words_user_id'), 'known_words', ['user_id'], unique=False)
    op.create_index('ix_known_words_user_word', 'known_words', ['user_id', 'word'], unique=True)
    op.create_table('stopwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('algo_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.CheckConstraint("algo_type IN ('longest_match', 'tokenization')", name='ck_stopwords_algo_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stopwords_user_id'), 'stopwords', ['user_id'], unique=False)
    op.create_index('ix_stopwords_user_word_algo', 'stopwords', ['user_id', 'word', 'algo_type'], unique=True)
    op.create_table('user_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('dictionary_word_id', sa.Integer(), nullable=True),
    sa.Column('freq_combined', sa.BigInteger(), nullable=True),
    sa.Column('hsk_v2_2012', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_v3_2021', sa.SmallInteger(), nullable=True),
    sa.Column('hsk_v3_2026', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_word_id'], ['dictionary_words.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_words_dictionary_word_id'), 'user_words', ['dictionary_word_id'], unique=False)
    op.create_index(op.f('ix_user_words_user_id'), 'user_words', ['user_id'], unique=False)
    op.create_index('ix_user_words_user_word', 'user_words', ['user_id', 'word'], unique=True)
    op.create_index(op.f('ix_user_words_word'), 'user_words', ['word'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_text_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.CheckConstraint("source IN ('trie', 'token', 'unknown')", name='ck_analysis_results_source'),
    sa.ForeignKeyConstraint(['input_text_id'], ['input_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_input_text_id'), 'analysis_results', ['input_text_id'], unique=False)
    op.create_index('ix_analysis_results_input_text_word', 'analysis_results', ['input_text_id', 'word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_results_input_text_word', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_input_text_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_user_words_word'), table_name='user_words')
    op.drop_index('ix_user_words_user_word', table_name='user_words')
    op.drop_index(op.f('ix_user_words_user_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_dictionary_word_id'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index('ix_stopwords_user_word_algo', table_name='stopwords')
    op.drop_index(op.f('ix_stopwords_user_id'), table_name='stopwords')
    op.drop_table('stopwords')
    op.drop_index('ix_known_words_user_word', table_name='known_words')
    op.drop_index(op.f('ix_known_words_user_id'), table_name='known_words')
    op.drop_table('known_words')
    op.drop_index(op.f('ix_input_texts_user_id'), table_name='input_texts')
    op.drop_table('input_texts')
    op.drop_index(op.f('ix_hsk_forms_entry_id'), table_name='hsk_forms')
    op.drop_table('hsk_forms')
    op.drop_index('ix_garbage_words_user_word', table_name='garbage_words')
    op.drop_index(op.f('ix_garbage_words_user_id'), table_name='garbage_words')
    op.drop_table('garbage_words')
    op.drop_index(op.f('ix_word_frequencies_word'), table_name='word_frequencies')
    op.drop_table('word_frequencies')
    op.drop_index(op.f('ix_hsk_entries_simplified'), table_name='hsk_entries')
    op.drop_table('hsk_entries')
    op.drop_index(op.f('ix_dictionary_words_word'), table_name='dictionary_words')
    op.drop_table('dictionary_words')
    # ### end Alembic commands ###
