"""add frequency columns and clean up dictionary_words

Revision ID: 8532f571cad6
Revises: 777314dda522
Create Date: 2026-08-16 20:49:52.222412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8532f571cad6'
down_revision: Union[str, Sequence[str], None] = '777314dda522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_words', sa.Column('frequency', sa.BigInteger(), nullable=True))
    op.drop_column('dictionary_words', 'freq_combined')
    op.add_column('word_frequencies', sa.Column('calc_combined', sa.BigInteger(), nullable=True))
    op.add_column('word_frequencies', sa.Column('frequency', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_frequencies', 'frequency')
    op.drop_column('word_frequencies', 'calc_combined')
    op.add_column('dictionary_words', sa.Column('freq_combined', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('dictionary_words', 'frequency')
    # ### end Alembic commands ###
