import { getPreference, setPreference } from './api';

// Account-level settings for the export feature (Account page's "Export"
// card, ExportDialog.svelte) - backend-persisted (key "export", via the
// generic app.modules.preferences mechanism), NOT localStorage like this
// app's other preferences (theme, word-detail-panel section defaults,
// context length) - see api.ts's getPreference/setPreference docstring.
// Shared by both export formats (Pleco .txt and .xlsx) - splitting the
// options by format is deliberately deferred (see ROADMAP.md).
export interface ExportPreferences {
	includePinyin: boolean;
	includeDefinitions: boolean;
	definitionSources: {
		corpusFrequency: boolean;
		hsk: boolean;
		cedict: boolean;
		userGlobal: boolean;
		userText: boolean;
		userAnalysis: boolean;
		autoGenerated: boolean;
	};
	includeFamiliarity: boolean;
	includeSampleSentences: boolean;
	includeContext: boolean;
	includeGlobalNote: boolean;
}

// Only applied when the backend has no "export" row yet for this user (a
// first-ever visit) - everything on, so the feature is immediately useful
// without a trip to the Account page first.
export const DEFAULT_EXPORT_PREFERENCES: ExportPreferences = {
	includePinyin: true,
	includeDefinitions: true,
	definitionSources: {
		corpusFrequency: true,
		hsk: true,
		cedict: true,
		userGlobal: true,
		userText: true,
		userAnalysis: true,
		autoGenerated: true,
	},
	includeFamiliarity: true,
	includeSampleSentences: true,
	includeContext: true,
	includeGlobalNote: true,
};

export async function loadExportPreferences(): Promise<ExportPreferences> {
	const { value } = await getPreference<Partial<ExportPreferences>>('export');
	if (!value) return DEFAULT_EXPORT_PREFERENCES;
	// Deep-merge over the defaults rather than a bare `value ?? default` -
	// a preference saved before this feature gained new toggles (autoGenerated,
	// includeFamiliarity/includeSampleSentences/includeContext/
	// includeGlobalNote) has a JSON blob missing those keys entirely, and a
	// shallow fallback would silently read them as undefined/off instead of
	// defaulting to on like every other toggle here.
	return {
		...DEFAULT_EXPORT_PREFERENCES,
		...value,
		definitionSources: {
			...DEFAULT_EXPORT_PREFERENCES.definitionSources,
			...(value.definitionSources ?? {}),
		},
	};
}

export async function saveExportPreferences(prefs: ExportPreferences): Promise<void> {
	await setPreference('export', prefs);
}
