// Pure formatter for Pleco's flashcard-import text format - no fetch, no
// DOM, easy to unit-test in isolation (same spirit as the backend's
// synthetic-dictionary segmenter tests). ExportDialog.svelte is the only
// caller: it gathers the inputs (which words to export, the bulk
// GET /analyze/{id}/export-data payload, the account's ExportPreferences)
// and hands them to buildPlecoExport, then downloads the result verbatim.
//
// Format (per Pleco's own official Import/Export manual page -
// iphone.pleco.com/manual/.../flash.html - not a forum guess): each card
// is EXACTLY one physical line, no exceptions -
//   //{Category}/{Subcategory}
//   word<TAB>pinyin<TAB>definition
// `//Category/Subcategory` is Pleco's real nested-category syntax. A blank
// pinyin or definition field is fine - Pleco looks the word up in its own
// dictionaries when a field is left empty, so there's no fallback
// placeholder to invent for a word with nothing resolved. Only one tab
// between fields, ever (Pleco's importer is picky about that), which is
// also why any literal tab/newline inside a word's own data gets
// neutralized in sanitizeField below rather than passed through.
//
// A real newline inside the definition field is NOT supported on import,
// full stop - confirmed against Pleco's own manual (no escape/quoting
// convention is documented for it) after a private-use-character trick
// from forum folklore turned out not to work on a real device (everything
// ran together with no separation at all). Newlines only ever work when
// editing a card's text by hand afterward, inside Pleco itself - never
// through the importer. So instead of a line break, this field uses two
// levels of plain visual separator: PLECO_ITEM_SEP between lines within
// one source's own block (e.g. between two HSK forms, or between
// meanings), PLECO_BLOCK_SEP between different sources - confirmed with
// the user as the best available approximation of "newline within a
// field, blank line between fields" given the format's real constraint.
//
// Given how dense one physical line already is, this field is also more
// aggressive than xlsxExport.ts's columns about omitting empty sub-fields
// entirely (no "classifiers: " with nothing after it) rather than
// matching the Excel template's always-show-the-label convention - a
// crowded single line has much less room for that kind of placeholder
// than a spacious cell does, per the user's own call. That's what the
// PlecoItem/renderPlecoItems machinery below is for: build every
// candidate field unconditionally, then let rendering drop whichever ones
// turned out blank - exportData.ts's own hskLines/cedictLines/
// userEntryLines/autoGeneratedLines stay exactly as they are (still used
// by xlsxExport.ts, unaffected by any of this).

import { sourceCategory, familiarityLabel, type SourceCategory } from './wordDisplay';
import type { ExportPreferences } from './exportPreferences';
import {
	corpusLines,
	filterUserEntries,
	exportUserEntryLabel,
	contextToPlainText,
	type ExportWordData,
	type ExportUserEntry,
	type ExportableWord,
} from './exportData';

const CATEGORY_LABELS: Record<SourceCategory, string> = {
	main: 'Main',
	extra: 'Extra',
};

// Separates lines within one source's own block (e.g. between two HSK
// forms, or between one meaning and the next) - see this file's own
// docstring for why this is a plain visual separator and not a real line
// break.
const PLECO_ITEM_SEP = ' / ';
// Separates different sources' blocks from each other, a visually
// heavier break than PLECO_ITEM_SEP so the two nesting levels ("another
// line in this same source" vs. "a completely different source") stay
// tellable apart at a glance.
const PLECO_BLOCK_SEP = ' | ';

// Neutralizes characters that would corrupt the tab-separated, one-
// card-per-line format if they slipped through from a word/pinyin/
// definition's own data - a literal tab would misalign the 3 fields, and
// a literal newline would split one card's single physical line into two
// (Pleco reads one card per line - see this file's own docstring). Any
// such newline collapses to a plain space, not one of the separators
// above - an incidental newline embedded in someone's own free-text (a
// note, a sample sentence) isn't a source/item boundary, so it shouldn't
// borrow that visual language.
function sanitizeField(text: string): string {
	return text.replace(/\t/g, ' ').replace(/\r\n|\r|\n/g, ' ');
}

// One candidate piece of a source's block - built unconditionally (every
// form/sense/entry contributes one of each), with the actual "does this
// have anything to show" decision left to renderPlecoItems. A 'heading'
// always renders (it's an index/scope label, not a value that can be
// missing); a 'field' renders as "label: value" only when value is
// present, otherwise it's dropped entirely (no dangling "classifiers: ");
// a 'list' renders as "label: item / item / ..." only when non-empty -
// the label sits directly against the first item (no separator between
// them), with PLECO_ITEM_SEP appearing only *between* items, per the
// user's own correction ("no reason to have the slash there - only
// slashes between meanings").
type PlecoItem =
	| { kind: 'heading'; text: string }
	| { kind: 'field'; label: string; value: string | null }
	| { kind: 'list'; label: string; items: string[] };

function renderPlecoItems(items: PlecoItem[]): string {
	return items
		.map((item): string | null => {
			if (item.kind === 'heading') return item.text;
			if (item.kind === 'field') return item.value ? `${item.label}: ${item.value}` : null;
			return item.items.length > 0 ? `${item.label}: ${item.items.join(PLECO_ITEM_SEP)}` : null;
		})
		.filter((s): s is string => s !== null)
		.join(PLECO_ITEM_SEP);
}

// HSK: every form (heading + traditional/pinyin/meanings/classifiers,
// each individually omitted if blank), then the entry-level fields
// (radical/level-per-edition/HSK frequency rank/POS), same content and
// order as exportData.ts's hskLines but rendered compactly. Omitted
// entirely when there's no HSK entry for this word at all.
function hskPlecoItems(word: ExportWordData): PlecoItem[] | null {
	const hasEntry =
		word.hsk_forms.length > 0 ||
		!!word.hsk_radical ||
		word.hsk_frequency != null ||
		word.hsk_pos.length > 0 ||
		word.hsk_v2_2012 != null ||
		word.hsk_v3_2021 != null ||
		word.hsk_v3_2026 != null;
	if (!hasEntry) return null;

	const items: PlecoItem[] = [];
	word.hsk_forms.forEach((form, i) => {
		items.push({ kind: 'heading', text: `Form ${i + 1}` });
		items.push({ kind: 'field', label: 'traditional', value: form.traditional });
		items.push({ kind: 'field', label: 'pinyin', value: form.pinyin });
		items.push({ kind: 'list', label: 'meanings', items: form.meanings });
		items.push({ kind: 'field', label: 'classifiers', value: form.classifiers.length > 0 ? form.classifiers.join(', ') : null });
	});

	if (word.hsk_radical) items.push({ kind: 'field', label: 'Radical', value: word.hsk_radical });
	if (word.hsk_v2_2012 != null || word.hsk_v3_2021 != null || word.hsk_v3_2026 != null) {
		// "N/A" for a missing edition, not "-" - the value already uses "-"
		// to separate the three editions, so a bare "-" would be ambiguous.
		items.push({
			kind: 'field',
			label: 'Level',
			value: `2012: ${word.hsk_v2_2012 ?? 'N/A'} - 2021: ${word.hsk_v3_2021 ?? 'N/A'} - 2026: ${word.hsk_v3_2026 ?? 'N/A'}`,
		});
	}
	if (word.hsk_frequency != null) items.push({ kind: 'field', label: 'HSK Frequency Rank', value: String(word.hsk_frequency) });
	if (word.hsk_pos.length > 0) items.push({ kind: 'field', label: 'POS', value: word.hsk_pos.join(', ') });
	return items;
}

// CC-CEDICT: every sense (heading + traditional/pinyin/meanings), same
// content/order as exportData.ts's cedictLines. Omitted when there are no
// senses at all.
function cedictPlecoItems(word: ExportWordData): PlecoItem[] | null {
	if (word.cedict_senses.length === 0) return null;
	const items: PlecoItem[] = [];
	word.cedict_senses.forEach((sense, i) => {
		items.push({ kind: 'heading', text: `Sense ${i + 1}` });
		items.push({ kind: 'field', label: 'traditional', value: sense.traditional });
		items.push({ kind: 'field', label: 'pinyin', value: sense.pinyin });
		items.push({ kind: 'list', label: 'meanings', items: sense.definitions });
	});
	return items;
}

// User: every entry (already filtered to the enabled scopes by the
// caller), heading + pinyin/meaning/note. Omitted when the filtered list
// is empty.
function userPlecoItems(entries: ExportUserEntry[]): PlecoItem[] | null {
	if (entries.length === 0) return null;
	const items: PlecoItem[] = [];
	entries.forEach((entry) => {
		items.push({ kind: 'heading', text: exportUserEntryLabel(entry) });
		items.push({ kind: 'field', label: 'pinyin', value: entry.pronunciation });
		items.push({ kind: 'list', label: 'meanings', items: entry.meaning ? [entry.meaning] : [] });
		items.push({ kind: 'field', label: 'note', value: entry.notes });
	});
	return items;
}

// Auto-Generated: unlike every block above, this one still shows its
// labels even when a piece is blank (see exportData.ts's autoGeneratedLines
// docstring - a blank state here is itself meaningful, "nothing generated
// yet"), so its two fields aren't candidates for the usual omit-if-blank
// treatment; the whole block is still omitted when *nothing* at all has
// been generated for this word.
function autoGeneratedPlecoItems(word: ExportWordData): PlecoItem[] | null {
	if (!word.enrichment_pinyin && !word.enrichment_translation) return null;
	return [
		{ kind: 'field', label: 'pinyin', value: word.enrichment_pinyin ?? '' },
		{ kind: 'list', label: 'meanings', items: word.enrichment_translation ? [word.enrichment_translation] : [] },
	];
}

// Builds one word's definition field from whichever sources are enabled
// in `prefs` and actually resolved something for this word. A single
// resolved block is left unprefixed; two or more get each source's own
// label prefixed to its text (matching how WordDetailPanel's "Dictionary"/
// "Your entries" sections already read) so a user opening the card in
// Pleco can tell which source said what, joined with PLECO_BLOCK_SEP.
function definitionField(word: ExportWordData, prefs: ExportPreferences): string {
	const sources = prefs.definitionSources;
	const blocks: { label: string; text: string }[] = [];

	if (sources.corpusFrequency) {
		const lines = corpusLines(word);
		if (lines) blocks.push({ label: 'Corpus', text: lines.filter((l) => l !== '').join(PLECO_ITEM_SEP) });
	}
	if (sources.hsk) {
		const items = hskPlecoItems(word);
		if (items) blocks.push({ label: 'HSK', text: renderPlecoItems(items) });
	}
	if (sources.cedict) {
		const items = cedictPlecoItems(word);
		if (items) blocks.push({ label: 'CC-CEDICT', text: renderPlecoItems(items) });
	}
	const userItems = userPlecoItems(filterUserEntries(word.user_entries, sources));
	if (userItems) blocks.push({ label: 'User', text: renderPlecoItems(userItems) });
	if (sources.autoGenerated) {
		const items = autoGeneratedPlecoItems(word);
		if (items) blocks.push({ label: 'Auto-Generated', text: renderPlecoItems(items) });
	}
	if (prefs.includeFamiliarity && word.familiarity != null) {
		blocks.push({ label: 'Familiarity', text: familiarityLabel(word.familiarity) });
	}
	if (prefs.includeSampleSentences && word.sample_sentences.length > 0) {
		blocks.push({ label: 'Sample Sentences', text: word.sample_sentences.join(PLECO_ITEM_SEP) });
	}
	if (prefs.includeContext && word.contexts.length > 0) {
		blocks.push({ label: 'Context(s)', text: word.contexts.map(contextToPlainText).join(PLECO_ITEM_SEP) });
	}
	if (prefs.includeGlobalNote && word.note) {
		blocks.push({ label: 'Global Note', text: word.note });
	}

	if (blocks.length === 0) return '';
	if (blocks.length === 1) return sanitizeField(blocks[0].text);
	return sanitizeField(blocks.map((b) => `${b.label}: ${b.text}`).join(PLECO_BLOCK_SEP));
}

// `categoryTitle` is the text's title (already resolved by the caller -
// falls back to something sensible there, e.g. "Untitled text", since this
// function has no opinion on that). `wordsToExport` decides which words go
// in at all (the caller applies "respect current filter" or not before
// calling this) and which of the 2 subcategories each lands in, via
// sourceCategory(w.is_main_segmentation) - `exportData` supplies everything
// else, looked up by word. A word present in `wordsToExport` but missing
// from `exportData` (shouldn't happen - the backend returns every word in
// the analysis) just gets blank pinyin/definition fields, same as any
// other word with nothing resolved.
export function buildPlecoExport(
	categoryTitle: string,
	wordsToExport: ExportableWord[],
	exportData: ExportWordData[],
	prefs: ExportPreferences
): string {
	const dataByWord = new Map(exportData.map((w) => [w.word, w]));
	const byCategory: Record<SourceCategory, string[]> = { main: [], extra: [] };

	for (const w of wordsToExport) {
		const data = dataByWord.get(w.word);
		const pinyin = prefs.includePinyin ? sanitizeField(data?.pinyin ?? '') : '';
		const definition = prefs.includeDefinitions && data ? definitionField(data, prefs) : '';
		byCategory[sourceCategory(w.is_main_segmentation)].push(`${sanitizeField(w.word)}\t${pinyin}\t${definition}`);
	}

	const sections: string[] = [];
	for (const category of ['main', 'extra'] as const) {
		const lines = byCategory[category];
		if (lines.length === 0) continue;
		sections.push(`//${categoryTitle}/${CATEGORY_LABELS[category]}`);
		sections.push(...lines);
	}
	return sections.join('\n');
}
