import { browser } from '$app/environment';

// Supersedes the earlier enrichmentVisibilityPersistence.ts, which only
// covered the Auto-generated section - generalized to all 8 collapsible
// sections in WordDetailPanel.svelte once every section got the same
// chevron toggle that one originally introduced.
export type PanelSectionId =
	| 'corpus'
	| 'hsk'
	| 'cedict'
	| 'autoGenerated'
	| 'userWords'
	| 'sampleSentences'
	| 'note'
	| 'visibility';

export const SECTION_ORDER: PanelSectionId[] = [
	'corpus',
	'hsk',
	'cedict',
	'autoGenerated',
	'userWords',
	'sampleSentences',
	'note',
	'visibility',
];

export const SECTION_LABELS: Record<PanelSectionId, string> = {
	corpus: 'Corpus frequency',
	hsk: 'HSK',
	cedict: 'CC-CEDICT',
	autoGenerated: 'Auto-generated',
	userWords: 'Your entries',
	sampleSentences: 'Sample sentences',
	note: 'Note',
	visibility: 'Visibility',
};

// Collapsed-by-default when a word's panel first shows a section it has no
// per-word override for (see isSectionCollapsed below) - user-configurable
// from /profile's Preferences section (see getSectionDefaults/
// setSectionDefault), these are just the out-of-the-box starting point.
// "Note" wasn't part of the original request that named defaults for the
// other 7 sections - defaulted to shown, matching most of the others,
// rather than guessing it belonged with the two hidden-by-default ones.
const FACTORY_DEFAULTS: Record<PanelSectionId, boolean> = {
	corpus: false,
	hsk: false,
	cedict: false,
	userWords: false,
	sampleSentences: false,
	note: false,
	autoGenerated: true,
	visibility: true,
};

const DEFAULTS_STORAGE_KEY = 'mandarin_tools_section_defaults';
const OVERRIDE_STORAGE_PREFIX = 'mandarin_tools_section_collapsed:';

// The global "collapsed by default" preference per section - one shared
// value across every word, read/written from /profile's Preferences
// section. localStorage (a real lasting preference, not disposable
// interruption-recovery state - see panelWordPersistence.ts's docstring
// for that distinction), matching the choice +page.svelte's own filter-bar
// preferences already made for the same reason.
export function getSectionDefaults(): Record<PanelSectionId, boolean> {
	if (!browser) return { ...FACTORY_DEFAULTS };
	try {
		const raw = localStorage.getItem(DEFAULTS_STORAGE_KEY);
		if (!raw) return { ...FACTORY_DEFAULTS };
		const stored = JSON.parse(raw) as Partial<Record<PanelSectionId, boolean>>;
		return { ...FACTORY_DEFAULTS, ...stored };
	} catch {
		return { ...FACTORY_DEFAULTS };
	}
}

export function setSectionDefault(section: PanelSectionId, collapsed: boolean): void {
	if (!browser) return;
	try {
		const current = getSectionDefaults();
		current[section] = collapsed;
		localStorage.setItem(DEFAULTS_STORAGE_KEY, JSON.stringify(current));
	} catch {
		// e.g. storage disabled/full - the preference just won't stick, no need to surface an error
	}
}

// Per-word overrides - keyed by word alone (not page/path), same reasoning
// as enrichmentVisibilityPersistence.ts's original docstring: a section
// someone's collapsed/expanded for a given word is equally true wherever
// that word's panel is next opened. Every explicit toggle is recorded here
// and stays pinned from then on, even if it happens to match whatever the
// global default currently is - "changed" means changed, not "changed to
// something other than the default" - so a later change to the global
// default never silently overrides a word the user has actually touched.
function getWordOverrides(word: string): Partial<Record<PanelSectionId, boolean>> {
	if (!browser) return {};
	try {
		const raw = localStorage.getItem(`${OVERRIDE_STORAGE_PREFIX}${word}`);
		return raw ? (JSON.parse(raw) as Partial<Record<PanelSectionId, boolean>>) : {};
	} catch {
		return {};
	}
}

// The one function WordDetailPanel.svelte actually needs to decide a
// section's collapsed state for the word it's currently showing: this
// word's own override if it has one, otherwise the live global default -
// which is what makes "a word nobody's touched follows the defaults"
// true even after the defaults themselves change later.
export function isSectionCollapsed(word: string, section: PanelSectionId): boolean {
	const overrides = getWordOverrides(word);
	if (section in overrides) return overrides[section]!;
	return getSectionDefaults()[section];
}

export function setSectionCollapsedForWord(word: string, section: PanelSectionId, collapsed: boolean): void {
	if (!browser) return;
	try {
		const overrides = getWordOverrides(word);
		overrides[section] = collapsed;
		localStorage.setItem(`${OVERRIDE_STORAGE_PREFIX}${word}`, JSON.stringify(overrides));
	} catch {
		// e.g. storage disabled/full - the toggle just won't be remembered next time, no need to surface an error
	}
}
