// .xlsx counterpart to pleco.ts - same inputs (the account's
// ExportPreferences, the bulk GET /analyze/{id}/export-data payload, and
// whichever words the dialog decided to include), reshaped for a
// spreadsheet: one sheet per bucket (Main/Extra, only the
// non-empty ones - same omission rule pleco.ts uses) with the 12-column
// layout the user specified (word/segmentation-source/count/corpus/HSK/
// CC-CEDICT/user/auto-generated/familiarity/sample-sentences/context/
// global-note), each multi-line cell using a real "\n" (rendered via
// wrapText) rather than Pleco's U+EAB1 hack - this is a real spreadsheet
// cell, not a single flashcard field, so there's no reason to cram
// multiple sources into one cell either: every source gets its own column
// instead of pleco.ts's joined-and-labeled field.
//
// Uses `exceljs`, not the far more commonly reached-for `xlsx` (SheetJS) -
// SheetJS's npm-published package has two unpatched high-severity
// advisories (prototype pollution, ReDoS) with "no fix available" via npm.
// Both only matter for *parsing* untrusted spreadsheets, which this app
// never does, but there was no reason to accept even an unused risk while
// a clean alternative existed. The Context column below is why this
// module moved off `write-excel-file` (last session's choice) onto
// exceljs specifically: bolding just the matched word within a cell needs
// a real rich-text run (multiple differently-styled spans in one cell
// value), which write-excel-file's API has no way to express at all -
// exceljs's `{richText: [...]}` cell value is a standard, first-class
// feature built for exactly this. (exceljs carries one moderate advisory
// itself, transitively through `uuid`'s v3/v5/v6-with-an-explicit-buffer
// bug - a narrow, Node-Buffer-specific misuse pattern this module's own
// browser, write-only, no-untrusted-input usage never exercises. See
// BUGS.md/ROADMAP.md if that tradeoff ever needs revisiting.)
//
// Loaded via dynamic import (see buildXlsxBlob) rather than a static
// top-level import, so choosing the Pleco format never pays for this
// library's bundle weight at all.

import { sourceCategory, type SourceCategory } from './wordDisplay';
import type { ExportPreferences } from './exportPreferences';
import {
	segmentationSourceText,
	corpusLines,
	hskLines,
	cedictLines,
	userEntryLines,
	filterUserEntries,
	autoGeneratedLines,
	type ExportWordData,
	type ExportContext,
	type ExportableWord,
} from './exportData';
import type { CellValue } from 'exceljs';

const SHEET_NAMES: Record<SourceCategory, string> = {
	main: 'Main',
	extra: 'Extra',
};

const HEADERS = [
	'Word',
	'Segmentation Source',
	'Count',
	'Corpus',
	'HSK',
	'CC-CEDICT',
	'User',
	'Auto-Generated',
	'Familiarity',
	'Sample Sentences',
	'Context',
	'Global Note',
] as const;

// Rough display widths, in "characters" - single-line columns stay
// narrow, multi-line-block columns get enough room that wrapped text is
// actually readable rather than a tall, narrow ribbon.
const WIDTHS: Record<(typeof HEADERS)[number], number> = {
	Word: 14,
	'Segmentation Source': 20,
	Count: 8,
	Corpus: 20,
	HSK: 50,
	'CC-CEDICT': 50,
	User: 50,
	'Auto-Generated': 30,
	Familiarity: 10,
	'Sample Sentences': 40,
	Context: 50,
	'Global Note': 30,
};

// The Context column's one bit of real formatting: `match` in each
// occurrence rendered as a bold rich-text run, `before`/`after` plain,
// occurrences separated by a real newline. Returns a plain '' for no
// occurrences (so the cell stays a normal blank string, not an empty
// richText value, which some viewers render oddly) and a bare string
// isn't used for a single occurrence either - richText is still needed
// there for the bold run.
function contextCellValue(contexts: ExportContext[]): CellValue {
	if (contexts.length === 0) return '';
	const runs: { font?: { bold: true }; text: string }[] = [];
	contexts.forEach((c, i) => {
		if (c.before) runs.push({ text: c.before });
		runs.push({ font: { bold: true }, text: c.match });
		const after = c.after + (i < contexts.length - 1 ? '\n' : '');
		if (after) runs.push({ text: after });
	});
	return { richText: runs };
}

// One row's 12 cell values, in column order. `wrapText` is applied
// uniformly to every cell of every data row by the caller (harmless on
// the single-line ones) rather than computed per-cell here.
function buildRowValues(w: ExportableWord, data: ExportWordData | undefined, prefs: ExportPreferences): CellValue[] {
	if (!data) {
		return [w.word, '', w.count ?? null, '', '', '', '', '', '', '', '', ''];
	}

	// `includeDefinitions` is the master switch (Account page: the
	// definition-source checkboxes only even show while it's on) - every
	// definition-sourced column respects it, same as Pleco's definitionField
	// only being called at all when it's on.
	const sources = prefs.definitionSources;
	const defsOn = prefs.includeDefinitions;
	const corpus = defsOn && sources.corpusFrequency ? corpusLines(data) : null;
	const hsk = defsOn && sources.hsk ? hskLines(data) : null;
	const cedict = defsOn && sources.cedict ? cedictLines(data) : null;
	const user = defsOn ? userEntryLines(filterUserEntries(data.user_entries, sources)) : null;
	const autoGenerated = defsOn && sources.autoGenerated ? autoGeneratedLines(data) : null;

	return [
		w.word,
		segmentationSourceText(data),
		w.count ?? null,
		corpus?.join('\n') ?? '',
		hsk?.join('\n') ?? '',
		cedict?.join('\n') ?? '',
		user?.join('\n') ?? '',
		autoGenerated?.join('\n') ?? '',
		prefs.includeFamiliarity ? data.familiarity : null,
		prefs.includeSampleSentences ? data.sample_sentences.join('\n') : '',
		prefs.includeContext ? contextCellValue(data.contexts) : '',
		prefs.includeGlobalNote ? (data.note ?? '') : '',
	];
}

// Same shape/reasoning as buildPlecoExport (pleco.ts): gathers the same
// inputs, returns a Blob (ExportDialog.svelte downloads either format the
// same way, via its own shared downloadBlob helper) instead of a string.
export async function buildXlsxBlob(
	wordsToExport: ExportableWord[],
	exportData: ExportWordData[],
	prefs: ExportPreferences
): Promise<Blob> {
	const ExcelJS = (await import('exceljs')).default;

	const dataByWord = new Map(exportData.map((w) => [w.word, w]));
	const byCategory: Record<SourceCategory, ExportableWord[]> = { main: [], extra: [] };
	for (const w of wordsToExport) {
		byCategory[sourceCategory(w.is_main_segmentation)].push(w);
	}

	const workbook = new ExcelJS.Workbook();
	let sheetCount = 0;

	for (const category of ['main', 'extra'] as const) {
		const words = byCategory[category];
		if (words.length === 0) continue;
		sheetCount++;

		const sheet = workbook.addWorksheet(SHEET_NAMES[category], {
			// Keeps the header row visible while scrolling a long sheet.
			views: [{ state: 'frozen', ySplit: 1 }],
		});
		sheet.columns = HEADERS.map((header) => ({ header, width: WIDTHS[header] }));
		sheet.getRow(1).font = { bold: true };

		for (const w of words) {
			const row = sheet.addRow(buildRowValues(w, dataByWord.get(w.word), prefs));
			row.eachCell({ includeEmpty: true }, (cell) => {
				cell.alignment = { wrapText: true, vertical: 'top' };
			});
		}
	}

	if (sheetCount === 0) {
		throw new Error('No words to export');
	}

	const buffer = await workbook.xlsx.writeBuffer();
	return new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}
